name: Release
on:
  push:
    branches: [ master ]
  pull_request:
  branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
  steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      - name: Run a multi-line script
        run: |
          npm install
          node_modules/pkg/lib-es5/bin.js run.js