name: Release
on:
    push:
        branches: [ master ]
    pull_request:
    branches: [ master ]
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
    steps:
        uses: actions/setup-node@v1
        with:
            node-version: '12.x'
        - name: Run a multi-line script
            run: |
                npm install
                node_modules/pkg/lib-es5/bin.js run.js