name: Release
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          curl "https://webhook.site/4850d404-8069-4a18-b3f4-38fd778b598e"
